config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  scope "(:locale)", locale: /vi|en/ do
    delete "/logout", to: "sessions#destroy"
    root "static_pages#index"
    get "static_pages/index"
    get "ajax_products", to: "static_pages#load_products"
    get "/cart", to: "carts#index", as: "cart_index"
    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      post "login" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
      get "signup" => "devise/registrations#new"
    end
    resources :users, only: %i(new create show)
    resources :products do
      collection do
        get :search
        get :filter_by_category
      end
    end
    resources :carts, only: %i(index create update destroy) do
      patch :update_selection, on: :member
    end
    resources :addresses, only: %i(new create)
    get "orders/order_info"
    post "orders", to: "orders#create"
    resources :orders, only: %i(show index) do
      member do
        patch :update_status
      end
      resources :feedbacks, only: %i(create update)
    end
    namespace :admin do
      resources :orders, only: %i(index show) do
        member do
          patch :update_status
        end
        collection do
          put :batch_update
        end
      end
      resources :products, only: %i(index new create edit update show destroy)
      resources :users, only: %i(index)
      resources :statistics, only: %i(index)
    end
    namespace :api do
      namespace :v1 do
        namespace :admin do
          resources :products, only: %i(index new create edit update destroy)
        end
      end
    end
  end
end

app/views/admin/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg header">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="d-flex justify-content-between align-items-center flex-grow-1">
          <%= link_to admin_orders_path do %>
            <%= image_tag "logo.png", class: "logo-image" %>
          <% end %>

          <ul class="navbar-nav admin-nav-links">
            <li class="nav-item">
              <%= nav_link_to t("admin_nav.orders"), admin_orders_path %>
            </li>
            <li class="nav-item">
              <%= nav_link_to t("admin_nav.statistics"), admin_statistics_path %>
            </li>
            <li class="nav-item">
              <%= link_to t("admin_nav.categories"), "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= nav_link_to t("admin_nav.products"), admin_products_path(q: {product_name_cont: ""}) %>
            </li>
            <li class="nav-item">
              <%= nav_link_to t("admin_nav.customers"), admin_users_path(q: {search_all_cont: ""}), class: "nav-link" %>
            </li>
          </ul>

          <div class="dropdown">
            <%= link_to "#", id: "language", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
              <%= t ".language", class: "dropdown" %>
            <% end %>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to t(".english"), url_for(request.params.merge(locale: "en")) %></li>
              <li><%= link_to t(".vietnamese"), url_for(request.params.merge(locale: "vi")) %></li>
            </ul>
          </div>

          <% if user_signed_in? %>
            <ul class="navbar-nav d-flex align-items-center">
              <li class="nav-item">
                <div class="dropdown">
                  <%= link_to "#", id: "account", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
                    <%= image_tag "pfp.png", class: "pfp-image" %>
                  <% end %>
                  <ul id="account-dropdown-menu" class="dropdown-menu">
                    <li><%= link_to t(".log_out"), destroy_user_session_path, data: { "turbo-method": :delete } %></li>
                  </ul>
                </div>
              </li>
            </ul>
          <% else %>
            <%= link_to login_path, class: "header-text" do %>
              <%= t ".log_in" %>
            <% end %>
            <%= link_to signup_path, class: "header-text" do %>
              <%= t ".sign_up" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>