config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  scope "(:locale)", locale: /vi|en/ do
    delete "/logout", to: "sessions#destroy"
    root "static_pages#index"
    get "static_pages/index"
    get "ajax_products", to: "static_pages#load_products"
    get "/cart", to: "carts#index", as: "cart_index"
    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      post "login" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
      get "signup" => "devise/registrations#new"
    end
    resources :users, only: %i(new create show)
    resources :products do
      collection do
        get :search
        get :filter_by_category
      end
    end
    resources :carts, only: %i(index create update destroy) do
      patch :update_selection, on: :member
    end
    resources :addresses, only: %i(new create)
    get "orders/order_info"
    post "orders", to: "orders#create"
    resources :orders, only: %i(show index) do
      member do
        patch :update_status
      end
      resources :feedbacks, only: %i(create update)
    end
    namespace :admin do
      resources :orders, only: %i(index show) do
        member do
          patch :update_status
        end
        collection do
          put :batch_update
        end
      end
      resources :products, only: %i(index new create edit update show destroy)
      resources :users, only: %i(index)
      resources :statistics, only: %i(index)
    end
    namespace :api do
      namespace :v1 do
        namespace :admin do
          resources :products, only: %i(index new create edit update destroy)
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :downcase_email
  ACCOUNT_PARAMS = %i(user_name email phone
                      password password_confirmation
                      remember_me).freeze

  enum role: {user: 0, admin: 1}, _prefix: true
  VALID_EMAIL_REGEX = Regexp.new(Settings.value.valid_email)
  VALID_PHONE_REGEX = Regexp.new(Settings.value.phone_format)

  validates :user_name, presence: true,
    length: {maximum: Settings.value.max_user_name}
  validates :email, presence: true,
    length: {maximum: Settings.value.max_user_email},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :password, presence: true,
    length: {minimum: Settings.value.min_user_password},
    allow_nil: true
  validates :phone, presence: true,
            length: {is: Settings.value.phone},
            format: {with: VALID_PHONE_REGEX}

  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :orders, dependent: :nullify
  has_one_attached :image

  def self.ransackable_attributes _auth_object = nil
    %w(
      created_at
      email
      id
      phone
      role
      updated_at
      user_name
    )
  end

  def self.ransackable_associations _auth_object = nil
    %w(
      addresses
      image_attachment
      image_blob
      orders
    )
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_orders, only: %i(index)
  before_action :find_order, only: %i(update_status show)

  def index
    @orders = @orders.sorted_by(params[:sort_by], params[:direction])
    @pagy, @orders = pagy @orders, limit: Settings.page_10
  end

  def show
    return unless find_order

    @pagy, @order_items = pagy(@order.order_items, items: Settings.page_10)
  end

  def update_status
    return unless find_order

    begin
      ActiveRecord::Base.transaction do
        handle_status_transition
      end
    rescue ActiveRecord::Rollback
      flash[:error] = t("admin.orders.orders_list.update_failed")
    ensure
      redirect_to request.referer || admin_orders_path
    end
  end

  def set_orders
    @current_status = determine_current_status
    @orders = Order.by_status(@current_status)
    @orders_count = Order.all
  end

  def batch_update
    order_ids = params[:order_ids] || []

    return redirect_no_orders if order_ids.blank?

    orders = Order.with_ids order_ids
    values = []

    orders.each do |order|
      process_order order, values
    end

    Order.import values, on_duplicate_key_update: [:status, :updated_at]
    redirect_to(
      request.referer || admin_orders_path,
      notice: t("orders.successfully_updated")
    )
  end

  private

  def status_valid?
    params[:status].present? && Order.statuses.key?(params[:status].to_sym)
  end

  def determine_current_status
    if status_valid?
      params[:status].to_sym
    else
      :all
    end
  end

  def handle_status_transition
    new_status = params[:status].to_sym
    case @order.status.to_sym
    when :pending
      handle_pending_status(new_status)
    when :preparing
      handle_preparing_status(new_status)
    when :in_transit
      handle_in_transit_status(new_status)
    else
      flash[:error] = t("admin.orders.orders_list.update_failed")
      raise ActiveRecord::Rollback
    end
  end

  def handle_pending_status new_status
    case new_status
    when :preparing
      prepare_order
    when :cancelled
      cancel_order
    else
      flash[:error] = t("admin.orders.orders_list.update_failed")
      raise ActiveRecord::Rollback
    end
  end

  def handle_preparing_status new_status
    if new_status == :in_transit
      update_order_status(:in_transit)
    else
      flash[:error] = t("admin.orders.orders_list.update_failed")
      raise ActiveRecord::Rollback
    end
  end

  def handle_in_transit_status new_status
    if new_status == :delivered
      update_order_status(:delivered)
    else
      flash[:error] = t("admin.orders.orders_list.update_failed")
      raise ActiveRecord::Rollback
    end
  end

  def prepare_order
    @order.update(status: :preparing)
    flash[:success] = t "admin.orders.orders_list.update_to_preparing"
  end

  def cancel_order
    if @order.cancel_order(role: :admin, refuse_reason: params[:refuse_reason])
      flash[:success] = t "admin.orders.orders_list.update_to_cancelled"
    else
      flash[:error] = t "admin.orders.orders_list.update_failed"
      raise ActiveRecord::Rollback
    end
  end

  def update_order_status new_status
    @order.update!(status: new_status)
    flash[:success] = t("admin.orders.orders_list.update_to_#{new_status}")
  end

  def find_order
    @order = Order.find_by(id: params[:id])
    unless @order
      flash[:error] = t("admin.orders.not_found")
      redirect_to admin_orders_path
      return false
    end
    true
  end

  def next_status_for order
    current_status_value = Order.statuses[order.status]
    next_status_value = current_status_value + 1
    Order.statuses.key(next_status_value)
  end

  def redirect_no_orders
    redirect_to(
      request.referer || admin_orders_path,
      alert: t("orders.no_orders_selected")
    )
  end

  def process_order order, values
    next_status = next_status_for order
    if next_status.nil?
      flash[:alert] = t("orders.cannot_transition", order_id: order.id)
      return
    end

    order.assign_attributes(status: next_status, updated_at: Time.current)
    values << order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource
  include OrdersHelper
  include FeedbacksHelper
  before_action :set_order_items_ids, :set_default_data, :set_order_items,
                only: %i(order_info create)
  before_action :set_orders, only: %i(index)
  before_action :find_order, only: %i(update_status show)

  def show
    @pagy, @order_items = pagy(
      @order.order_items,
      items: Settings.page_10
    )
    @order_items_with_feedback = @order.order_items.map do |order_item|
      {
        order_item:,
        feedback: feedback_for_order_item(order_item, current_user)
      }
    end
  end

  def order_info
    @order = Order.new
  end

  def create
    @order = current_user.orders.new order_params
    @order.total = calculate_total_amount @order_items_ids

    if @order.valid?
      process_order
    else
      flash.now[:error] = t "orders.order_info.messages.failed"
      render :order_info, status: :unprocessable_entity
    end
  end

  def set_orders
    @orders = fetch_orders
    @current_status = determine_current_status
    @orders_count = current_user.orders.recently_updated
  end

  def index
    @orders = @orders.sorted_by(params[:sort_by], params[:direction])
    @pagy, @orders = pagy @orders, limit: Settings.page_10
  end

  def update_status
    unless @order.status_pending? &&
           params[:status].to_sym == :cancelled
      return
    end

    cancel_order
    redirect_to request.referer || orders_path
  end

  private

  def set_default_data
    @addresses = current_user.addresses.sort_by_time
    @address = current_user.addresses.default_or_latest
  end

  def set_order_items
    @order_items = @order_items_ids.map do |id|
      cart = Cart.find_by(id:)
      product = Product.find_by id: cart&.product_id

      if cart.blank? || product.blank?
        flash[:warning] = t "flash.not_found_product"
        redirect_to carts_path and break
      end

      item_total = calculate_item_total(cart)
      {cart:, product:, item_total:}
    end
  end

  def order_params
    params.require(:order).permit Order::ORDER_PARAMS
  end

  def add_order_items
    @order_items.each do |item|
      @order.order_items.build(
        product_id: item[:product].id,
        quantity: item[:cart].quantity,
        price: item[:product].price
      )
    end
  end

  def handle_successful_order
    UpdateProductStockJob.perform_later(@order.order_items.as_json(
                                          only: %i(product_id quantity)
                                        ))
    @order.update paid_at: Time.current
    ClearCartJob.perform_later @order_items_ids
    cookies.delete(:cartitemids)
    cookies.delete(:total)
    flash[:success] = t "orders.order_info.messages.success"
    redirect_to orders_path
  end

  def handle_failed_order
    if @order.order_items.any?{|item| item.errors[:quantity].any?}
      flash[:error] = t "orders.order_info.messages.quantity"
      redirect_to carts_path and return
    end
    render :order_info, status: :unprocessable_entity
  end

  def process_order
    add_order_items
    if @order.save
      handle_successful_order
    else
      handle_failed_order
    end
  end

  def fetch_orders
    if status_valid?
      current_user.orders.by_status(params[:status].to_sym)
    else
      current_user.orders
    end
  end

  def status_valid?
    params[:status].present? && Order.statuses.key?(params[:status].to_sym)
  end

  def determine_current_status
    if status_valid?
      params[:status].to_sym
    else
      :all
    end
  end

  def cancel_order
    if @order.cancel_order(role: :user, refuse_reason: params[:refuse_reason])
      flash[:success] = t "admin.orders.orders_list.update_to_cancelled"
    else
      flash[:error] = t "admin.orders.orders_list.update_failed"
    end
  end

  def find_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:error] = t "orders.not_found"
    redirect_to orders_path
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def calculate_item_total cart
    product = Product.find_by id: cart.product_id
    cart.quantity * product.price
  end

  def calculate_total_amount order_items_ids
    order_items_ids.reduce(0) do |total_amount, id|
      cart = Cart.find_by(id:)
      total_amount + calculate_item_total(cart)
    end
  end

  def status_name status
    t "orders.statuses.#{status}"
  end

  def format_price price
    number_with_delimiter price, unit: "đ"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def calculate_item_total cart
    product = Product.find_by id: cart.product_id
    cart.quantity * product.price
  end

  def calculate_total_amount order_items_ids
    order_items_ids.reduce(0) do |total_amount, id|
      cart = Cart.find_by(id:)
      total_amount + calculate_item_total(cart)
    end
  end

  def status_name status
    t "orders.statuses.#{status}"
  end

  def format_price price
    number_with_delimiter price, unit: "đ"
  end

  def orders_sort_path sort_by, status, direction: "asc"
    if current_user.role_admin?
      admin_orders_path(sort_by:, status:, direction:)
    else
      orders_path(sort_by:, status:, direction:)
    end
  end

  def display_action_column? orders, current_user
    current_user.role_admin? && orders.any? do |order|
      %w(preparing in_transit).include? order.status.to_sym
    end ||
      orders.any?{|order| order.status.to_sym == :pending}
  end

  def address_options_for_select addresses
    if addresses.empty?
      options_for_select([], nil)
    else
      options = addresses.map{|a| [a.place, a.place]}
      default_address_place = addresses.find(&:default)&.place ||
                              addresses.first.place
      options_for_select(options, default_address_place)
    end
  end

  def status_classes order, status_value
    current_status_value = Order.statuses[order.status.to_sym]

    if order.status_cancelled?
      status_value == Order.statuses[:cancelled] ? "cancelled" : ""
    else
      status_value <= current_status_value ? "completed" : ""
    end
  end

  def line_classes order, index, statuses
    if order.status_cancelled?
      ""
    elsif index < statuses.length - 1
      next_status_value = statuses[index + 1][:value]
      current_status_value = Order.statuses[order.status.to_sym]

      if next_status_value <= current_status_value
        "completed"
      else
        ""
      end
    else
      ""
    end
  end

  def order_statuses
    Order.statuses.keys.map do |status_key|
      {
        name: status_name(status_key),
        value: Order.statuses[status_key]
      }
    end
  end

  def sortable column, title = nil
    title ||= t(".#{column}")
    direction = if column.to_s == params[:sort_by] &&
                   params[:direction] == "desc"
                  "asc"
                else
                  "desc"
                end
    link_to title, orders_sort_path(
      column, params[:status] || :all, direction:
    )
  end
end

app/views/admin/orders/_orders_list.html.erb
<tr>
  <% if order.status_pending? || order.status_preparing? || order.status_in_transit? %>
    <td><%= check_box_tag "order_ids[]", order.id %></td>
  <% end %>
  <td>
    <%= link_to "##{order.id}", admin_order_path(order) %>
  </td>
  <td class="product-image">
    <%= order_item_image(order, admin_order_path(order)) %>
  </td>
  <td><%= status_name(order.status) %></td>
  <td class="cart-container">
    <span class="total-price"><%= format_price order.total %></span>
  </td>
  <td>
    <div><%= order.created_at.strftime(Settings.time_format) %></div>
    <div><%= order.created_at.strftime(Settings.date_format) %></div>
  </td>
  <td>
    <div><%= order.updated_at.strftime(Settings.time_format) %></div>
    <div><%= order.updated_at.strftime(Settings.date_format) %></div>
  </td>
  <% if order.status_cancelled? %>
    <td><%= order.refuse_reason %></td>
  <% elsif order.status_delivered? %>
    <td><%= order.user.user_name %></td>
  <% else %>
    <td>
      <% case order.status.to_sym %>
      <% when :pending %>
        <%= button_to t(".update_to_preparing"), update_status_admin_order_path(order, status: :preparing), method: :patch, data: {turbo_confirm: t(".confirm_update_to_preparing")}, class: "btn btn-primary" %>
        <hr class="my-3">
        <%= form_with url: update_status_admin_order_path(order, status: :cancelled), method: :patch, local: true do |form| %>
          <div class="form-group">
            <%= form.label :refuse_reason, t("orders.orders_list.refuse_reason_by_admin") %>
            <%= form.text_area :refuse_reason, class: "form-control", required: true %>
          </div>
          <%= form.submit t(".cancel"), class: "btn btn-danger mt-2", data: {turbo_confirm: t(".confirm_cancel_order")} %>
        <% end %>
      <% when :preparing %>
        <%= button_to t(".update_to_in_transit"), update_status_admin_order_path(order, status: :in_transit), method: :patch, data: {turbo_confirm: t(".confirm_update_to_in_transit")}, class: "btn btn-primary" %>
      <% when :in_transit %>
        <%= button_to t(".update_to_delivered"), update_status_admin_order_path(order, status: :delivered), method: :patch, data: {turbo_confirm: t(".confirm_update_to_delivered")}, class: "btn btn-primary" %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/admin/orders/_status_list.html.erb
<div class="status-buttons">
  <%= link_to t("orders.status_list.all", count: @orders_count.count), admin_orders_path, class: "btn btn-outline-primary status-button #{@current_status == :all ? "active" : ""}", data: {turbo_frame: "order_list"} %>
  <% Order.statuses.keys.each do |status| %>
    <%= link_to "#{status_name(status)} (#{@orders_count.where(status: status).count})", admin_orders_path(status: status), class: "btn btn-outline-primary status-button #{@current_status == status.to_sym ? "active" : ""}", data: {turbo_frame: "order_list"} %>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<%= render partial: "admin/orders/status_list", locals: {orders_count: @orders_count, current_status: @current_status} %>

<div id="order_list">
  <turbo-stream action="replace" target="order_list">
    <template>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <%= form_with url: batch_update_admin_orders_path, method: :put do %>
              <% case @current_status %>
              <% when :pending %>
                <%= hidden_field_tag :new_status, :preparing %>
                <%= submit_tag t("admin.orders.orders_list.update_to_preparing"), data: { turbo_confirm: t("admin.orders.orders_list.confirm_update_to_preparing") }, class: "btn btn-primary" %>
              <% when :preparing %>
                <%= hidden_field_tag :new_status, :in_transit %>
                <%= submit_tag t("admin.orders.orders_list.update_to_in_transit"), data: { turbo_confirm: t("admin.orders.orders_list.confirm_update_to_in_transit") }, class: "btn btn-primary" %>
              <% when :in_transit %>
                <%= hidden_field_tag :new_status, :delivered %>
                <%= submit_tag t("admin.orders.orders_list.update_to_delivered"), data: { turbo_confirm: t("admin.orders.orders_list.confirm_update_to_delivered") }, class: "btn btn-primary" %>
              <% end %>
              <table class="table table-striped table-hover order-list">
                <%= render partial: "orders/orders_header" %>
                <tbody>
                  <%= render partial: "orders_list", collection: @orders, as: :order %>
                </tbody>
              </table>
            <% end %>
            <div class="pagination">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      </div>
    </template>
  </turbo-stream>
</div>

app/views/admin/orders/show.html.erb
<% provide :title, t("orders.show.title") %>
<h1><%= t "orders.show.title" %></h1>

<%= form_with model: @order, local: true do |form| %>
  <div class="order-status">
    <% order_statuses.each_with_index do |status, index| %>
      <div class="status-circle <%= status_classes(@order, status[:value]) %>">
        <%= status[:name] %>
      </div>
      <% if index < order_statuses.length - 1 %>
        <div class="status-line <%= line_classes(@order, index, order_statuses) %>"></div>
      <% end %>
    <% end %>
  </div>
  <div class="order-show">
    <div class="order-info-show">
      <div id="receive_info" class="receive_info">
        <%= render partial: "orders/order_history_info", locals: {order: @order} %>
      </div>
      <div id="payment-method" class="payment-method">
        <h4><%= t "orders.order_info.your_payment_method" %></h4>
        <div class="payment-methods">
          <div class="payment-option">
            <div class="payment-image">
              <% if @order.payment_method.to_sym == :vnpay %>
                <%= image_tag "vnpay_logo.avif", alt: "VNPay" %>
              <% else %>
                <%= image_tag "momo_logo.png", alt: "Momo" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="order_summary" class="order_summary">
      <div class="order-summary">
        <h3><%= t "orders.order_info.summary.title" %></h3>
        <div class="order-items-container">
          <% if @order_items.present? %>
            <%= render partial: "orders/order_history_item", collection: @order_items, as: :order_item %>
          <% else %>
            <p><%= t "orders.order_info.summary.empty_cart" %></p>
          <% end %>
        </div>
        <div class="order-summary-details">
          <p><strong><%= t "orders.order_info.summary.total" %></strong>
          <span class="total-price"><%= format_currency @order.total %></span></p>
        </div>
      </div>
    </div>
  </div>
<% end %>