config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  scope "(:locale)", locale: /vi|en/ do
    delete "/logout", to: "sessions#destroy"
    root "static_pages#index"
    get "static_pages/index"
    get "ajax_products", to: "static_pages#load_products"
    get "/cart", to: "carts#index", as: "cart_index"
    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      post "login" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
      get "signup" => "devise/registrations#new"
    end
    resources :users, only: %i(new create show)
    resources :products do
      collection do
        get :search
        get :filter_by_category
      end
    end
    resources :carts, only: %i(index create update destroy) do
      patch :update_selection, on: :member
    end
    resources :addresses, only: %i(new create)
    get "orders/order_info"
    post "orders", to: "orders#create"
    resources :orders, only: %i(show index) do
      member do
        patch :update_status
      end
      resources :feedbacks, only: %i(create update)
    end
    namespace :admin do
      resources :orders, only: %i(index show) do
        member do
          patch :update_status
        end
        collection do
          put :batch_update
        end
      end
      resources :products, only: %i(index new create edit update show destroy)
      resources :users, only: %i(index)
      resources :statistics, only: %i(index)
    end
    namespace :api do
      namespace :v1 do
        namespace :admin do
          resources :products, only: %i(index new create edit update destroy)
        end
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true,
    numericality: {greater_than: Settings.value.min_numeric}

  scope :by_id, ->(id){where(id:)}
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource
  before_action :find_cart_item, only: %i(update destroy)
  before_action :set_order_items_ids, only: :index
  before_action :logged_in_user, :init_data, only: %i(create update destroy)

  def index
    @pagy, @carts = pagy(
      current_user.carts.includes(:product),
      items: Settings.page_10
    )
    reset_selection
  end

  def create
    create_cart
    if @cart.save
      respond_to do |format|
        format.turbo_stream
        format.html{redirect_to product_path @cart.product}
      end
    else
      flash[:warning] = t "flash.add_to_cart_failed"
      redirect_to product_path params[:product_id]
    end
  end

  def update
    process_cart_update(params[:action_type]) if params[:action_type].present?

    handle_selection

    respond_to do |format|
      format.turbo_stream
      format.html{redirect_to product_path @cart.product}
    end
  end

  def destroy
    remove_cart_item_from_selection if selected_items.include?(@cart&.id)
    @cart.destroy
    update_count_and_total

    respond_to do |format|
      format.turbo_stream
      format.html{redirect_to product_path @cart.product}
    end
  end

  def update_selection
    find_cart_item_for_selection
    handle_selection

    respond_to do |format|
      format.turbo_stream
      format.html{redirect_to carts_path}
    end
  end

  private

  def handle_selection
    if params[:is_checked].present? || selected_items.include?(@cart&.id)
      update_selected_items
      update_selected_total
    end
    update_count_and_total
  end

  def remove_cart_item_from_selection
    items = selected_items
    items.delete @cart.id
    cookies[:cartitemids] = items.to_json

    update_selected_total
  end

  def update_count_and_total
    @count = selected_items_count || 0
    @total = formatted_selected_total || 0
  end

  def reset_selection
    cookies[:cartitemids] = [].to_json
    cookies[:total] = 0
    @count = 0
    @total = 0
  end

  def update_selected_items
    cart_id = params[:cart_id].to_i
    items = selected_items

    if params[:is_checked] == "true"
      items << cart_id unless items.include? cart_id
    else
      items.delete cart_id
    end

    cookies[:cartitemids] = items.to_json
  end

  def update_selected_total
    selected_carts = Cart.by_id selected_items
    total = selected_carts.sum{|cart| cart.quantity * cart.product.price}
    cookies[:total] = total.to_s
  end

  def selected_items
    JSON.parse(cookies[:cartitemids].presence || "[]").map(&:to_i)
  end

  def selected_items_count
    selected_items.size
  end

  def formatted_selected_total
    cookies[:total].to_i
  end

  def find_cart_item
    @cart = current_user.carts.find_by id: params[:id]
  end

  def find_cart_item_for_selection
    @cart = current_user.carts.find_by id: params[:cart_id]
  end

  def process_cart_update action_type
    case action_type.to_sym
    when :increment
      increment_cart_quantity
    when :decrement
      decrement_cart_quantity
    end
  end

  def increment_cart_quantity
    if @cart.product.nil?
      flash[:warning] = t "flash.not_found_product"
      redirect_to root_path and return
    end
    stock = @cart.product.stock || Settings.value.max_numeric
    if @cart.quantity < stock
      @cart.update quantity: @cart.quantity + 1
    else
      flash[:error] = t ".not_enough_stock"
    end
  end

  def decrement_cart_quantity
    @cart.update quantity: @cart.quantity - 1
    @cart.destroy if @cart.quantity <= 0
  end

  def create_cart
    product = Product.find params[:product_id]
    if product.stock&.zero?
      flash[:error] = t "flash.no_stock"
    elsif @cart.new_record? || @cart.quantity <= 0
      @cart = current_user.carts.new(product_id: params[:product_id],
                                     quantity: 1)
    else
      @cart.quantity += 1
    end
  end

  def init_data
    @product_id = params[:product_id]
    @cart ||= current_user.carts.find_or_initialize_by product_id: @product_id
    @cart.quantity ||= 0
  end

  def logged_in_user
    return if user_signed_in?

    flash[:warning] = t ".login_required"
    redirect_to login_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def format_price price
    number_with_delimiter price, unit: "đ"
  end

  def calculate_product_price product, quantity
    product.price * quantity
  end

  def total_cart_price carts
    total_price = carts.sum do |cart|
      calculate_product_price cart.product, cart.quantity
    end
    format_price total_price
  end
end

app/views/carts/_cart_button.html.erb
<% if cart && cart.quantity > 0 %>
  <div class="product-page-quantity-container">
    <%= button_to "-", cart_path(cart, action_type: "decrement", product_id: cart.product_id), method: :patch, class: "product-page-quantity-btn-minus product-page-quantity-btn", data: {turbo: "true"} %>
    <input type="text" class="product-page-quantity-input" value="<%= cart.quantity %>" readonly>
    <%= button_to "+", cart_path(cart, action_type: "increment", product_id: cart.product_id), method: :patch, class: "product-page-quantity-btn-plus product-page-quantity-btn", data: {turbo: "true"} %>
  </div>
<% else %>
  <%= button_to t(".add_to_cart"), carts_path(product_id: product_id), method: :post, class: "btn btn-primary", data: {turbo: "true"} %>
<% end %>

app/views/carts/_cart_details.html.erb
<tr id="cart_<%= cart.id %>">
  <td>
    <%= form_with url: update_selection_cart_path(cart), method: :patch, data: { turbo_stream: true } do %>
      <input type="checkbox" class="product-checkbox" name="is_checked" value="true">
      <%= hidden_field_tag :cart_id, cart.id %>
    <% end %>
  </td>
  <td class="product-image">
    <%= link_to product_path(cart.product) do %>
      <%= image_tag(resized_image(cart.product), alt: cart.product.product_name, class: "product-image") %>
    <% end %>
  </td>
  <td class="product-name">
    <%= link_to product_path(cart.product) do %>
      <%= cart.product.product_name %>
    <% end %>
  </td>
  <td class="product-price">
    <span class="value"><%= format_price cart.product.price %></span>
  </td>
  <td class="quantity-container" id="cart_page_<%= cart.product_id %>">
    <%= button_to "-", cart_path(cart, action_type: "decrement", product_id: cart.product_id), method: :patch, class: "quantity-btn", data: { turbo: "true" } %>
    <input type="text" class="quantity-input" value="<%= cart.quantity %>" readonly>
    <%= button_to "+", cart_path(cart, action_type: "increment", product_id: cart.product_id), method: :patch, class: "quantity-btn", data: { turbo: "true" } %>
  </td>
  <td class="total-price" id="total_price_<%= cart.product_id %>">
    <span class="value cart_<%= cart.id %>"><%= format_price(calculate_product_price(cart.product, cart.quantity)) %></span>
  </td>
  <td class="actions">
    <%= button_to image_tag("delete.png"), cart_path(cart, product_id: cart.product_id), method: :delete, class: "delete-button", data: { turbo: "true" } %>
  </td>
</tr>

app/views/carts/_cart_header.html.erb
<thead>
  <tr>
    <th><input type="checkbox" class="product-checkbox"></th>
    <th><%= t ".product" %></th>
    <th></th>
    <th><%= t ".price" %></th>
    <th><%= t ".quantity" %></th>
    <th><%= t ".total" %></th>
    <th><%= t ".action" %></th>
  </tr>
</thead>

app/views/carts/create.turbo_stream.erb
<% if current_user %>
  <%= turbo_stream.replace "cart_button_#{@cart.product_id}" do %>
    <div id="cart_button_<%= @cart.product_id %>">
      <%= render partial: "carts/cart_button", locals: {cart: @cart, product_id: @product_id} %>
    </div>
  <% end %>
<% end %>

app/views/carts/destroy.turbo_stream.erb
<%= turbo_stream.remove "cart_#{@cart.id}" %>

<%= turbo_stream.replace "cart_total_sum" do %>
  <div id="cart_total_sum">
    <p class="text-center total-price">
      (<span id="cart_items_count"><%= @count %></span><%= t ".product_count" %>)
      <span id="cart_items_total"><%= format_price @total %></span>
    </p>
  </div>
<% end %>

app/views/carts/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">

  <aside class="col-md-10">
    <% if @carts.any? %>
      <table class="cart-container">
        <%= render "cart_header" %>
        <tbody>
          <%= render partial: "cart_details", collection: @carts, as: :cart %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <div>
        <p><%= t ".empty_cart" %></p>
      </div>
    <% end %>
  </aside>
  <div class="col-md-2 d-flex flex-column">
    <div class="total-container">
      <h3 class="text-center title"><%= t ".total_cart" %></h3>
      <div id="cart_total_sum">
        <p class="text-center total-price">
          (<span id="cart_items_count">0</span><%= t ".product_count" %>)
          <span id="cart_items_total">0</span>
        </p>
      </div>
      <div class="d-flex justify-content-center mt-4 mb-4">
        <%= link_to t(".buy"), orders_order_info_path, class: "btn btn-buy" %>
    </div>
  </div>
</div>

app/views/carts/update.turbo_stream.erb
<%= turbo_stream.replace "cart_button_#{@cart.product_id}" do %>
  <div id="cart_button_<%= @cart.product_id %>">
    <%= render partial: "carts/cart_button", locals: {cart: @cart, product_id: @cart.product_id} %>
  </div>
<% end %>

<% if current_user %>
  <% if @cart.quantity > 0 %>
    <%= turbo_stream.replace "cart_page_#{@cart.product_id}" do %>
      <td class="quantity-container" id="cart_page_<%= @cart.product_id %>">
        <%= button_to "-", cart_path(@cart, action_type: "decrement", product_id: @cart.product_id), method: :patch, class: "quantity-btn", data: {turbo: "true"} %>
        <input type="text" class="quantity-input" value="<%= @cart.quantity %>" readonly>
        <%= button_to "+", cart_path(@cart, action_type: "increment", product_id: @cart.product_id), method: :patch, class: "quantity-btn", data: {turbo: "true"} %>
      </td>
    <% end %>

    <%= turbo_stream.replace "total_price_#{@cart.product_id}" do %>
      <td class="total-price" id="total_price_<%= @cart.product_id %>">
        <span class="value cart_<%= @cart.id %>"><%= format_price calculate_product_price(@cart.product, @cart.quantity) %></span>
      </td>
    <% end %>
  <% else %>
    <%= turbo_stream.remove "cart_#{@cart.id}" %>
  <% end %>
<% end %>

<%= turbo_stream.replace "cart_total_sum" do %>
  <div id="cart_total_sum">
    <p class="text-center total-price">
      (<span id="cart_items_count"><%= @count %></span><%= t ".product_count" %>)
      <span id="cart_items_total"><%= format_price @total %></span>
    </p>
  </div>
<% end %>

app/views/carts/update_selection.turbo_stream.erb
<%= turbo_stream.replace "cart_total_sum" do %>
  <div id="cart_total_sum">
    <p class="text-center total-price">
      (<span id="cart_items_count"><%= @count %></span><%= t ".product_count" %>)
      <span id="cart_items_total"><%= format_price @total %></span>
    </p>
  </div>
<% end %>