config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  scope "(:locale)", locale: /vi|en/ do
    delete "/logout", to: "sessions#destroy"
    root "static_pages#index"
    get "static_pages/index"
    get "ajax_products", to: "static_pages#load_products"
    get "/cart", to: "carts#index", as: "cart_index"
    devise_for :users
    as :user do
      get "login" => "devise/sessions#new"
      post "login" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
      get "signup" => "devise/registrations#new"
    end
    resources :users, only: %i(new create show)
    resources :products do
      collection do
        get :search
        get :filter_by_category
      end
    end
    resources :carts, only: %i(index create update destroy) do
      patch :update_selection, on: :member
    end
    resources :addresses, only: %i(new create)
    get "orders/order_info"
    post "orders", to: "orders#create"
    resources :orders, only: %i(show index) do
      member do
        patch :update_status
      end
      resources :feedbacks, only: %i(create update)
    end
    namespace :admin do
      resources :orders, only: %i(index show) do
        member do
          patch :update_status
        end
        collection do
          put :batch_update
        end
      end
      resources :products, only: %i(index new create edit update show destroy)
      resources :users, only: %i(index)
      resources :statistics, only: %i(index)
    end
    namespace :api do
      namespace :v1 do
        namespace :admin do
          resources :products, only: %i(index new create edit update destroy)
        end
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Searchable
  acts_as_paranoid
  PRODUCT_PARAMS = %i(category_id product_name image description price
                      stock).freeze
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :order_items # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :feedbacks, dependent: :destroy
  has_one_attached :image

  validates :category_id, presence: true
  validates :product_name, presence: true,
            length: {maximum: Settings.value.max_name}
  validates :description,
            length: {maximum: Settings.value.max_name}
  validates :price, presence: true,
            numericality: {greater_than_or_equal_to: Settings.value.min_numeric,
                           less_than_or_equal_to: Settings.value.max_numeric}
  validates :stock,
            allow_nil: true,
            numericality: {greater_than_or_equal_to: Settings.value.min_numeric,
                           less_than_or_equal_to: Settings.value.max_numeric}
  validates :rating,
            numericality: {greater_than_or_equal_to: Settings.value.min_numeric,
                           less_than_or_equal_to: Settings.value.rate_max},
            allow_nil: true

  delegate :category_name, to: :category, prefix: true

  scope(:featured, lambda do
    select(
      "products.*,
          (#{Settings.featured.rating_weight} * COALESCE(products.rating, 0) +
            #{Settings.featured.sold_weight} * COALESCE(products.sold, 0) +
            #{Settings.featured.feedback_weight} * COALESCE(
            COUNT(feedbacks.id), 0)) AS score,
          COUNT(feedbacks.id) AS feedback_count"
    )
      .joins("LEFT JOIN feedbacks ON feedbacks.product_id = products.id")
      .group("products.id")
      .having("products.rating >= #{Settings.featured.min_rating}")
      .order("score DESC")
      .limit(Settings.featured.limit)
  end)
  scope(:by_category_ids, lambda do |category_ids|
    where(category_id: category_ids) if category_ids.present?
  end)

  def self.search query,
    category_id: nil,
    price_gteq: nil,
    price_lteq: nil,
    rating_gteq: nil
    filter_conditions = []
    filter_conditions << {term: {category_id:}} if category_id.present?
    if price_gteq.present?
      filter_conditions << {range: {price: {gte: price_gteq}}}
    end
    if price_lteq.present?
      filter_conditions << {range: {price: {lte: price_lteq}}}
    end
    if rating_gteq.present?
      filter_conditions << {range: {rating: {gte: rating_gteq}}}
    end

    __elasticsearch__.search(
      {
        query: {
          function_score: {
            query: {
              bool: {
                must: [
                  {
                    match: {
                      product_name: {
                        query:,
                        fuzziness: "AUTO"
                      }
                    }
                  }
                ],
                filter: filter_conditions
              }
            },
            functions: [
              {
                script_score: {
                  script: {
                    lang: "painless",
                    params: {
                      rating_weight: Settings.featured.rating_weight,
                      sold_weight: Settings.featured.sold_weight,
                      feedback_weight: Settings.featured.feedback_weight
                    },
                    source: <<~SCRIPT
                      double rating_weight = params.rating_weight;
                      double sold_weight = params.sold_weight;
                      double feedback_weight = params.feedback_weight;

                      double rating = doc['rating'].size() != 0 ?
                        doc['rating'].value : 0.0;
                      double sold = doc['sold'].size() != 0 ?
                        doc['sold'].value : 0;
                      int feedback_count = doc['feedback_count'].size() != 0 ?
                        doc['feedback_count'].value : 0;

                      return (rating_weight * rating) +
                        (sold_weight * sold) +
                        (feedback_weight * feedback_count);
                    SCRIPT
                  }
                }
              }
            ],
            boost_mode: "sum"
          }
        }
      }
    )
  end

  scope(:top_selling_by_period, lambda do |period|
    time_range = case period
                 when "all_time"
                   nil
                 when "this_week"
                   Time.zone.now.beginning_of_week..Time.zone.now.end_of_week
                 when "this_month"
                   Time.zone.now.beginning_of_month..Time.zone.now.end_of_month
                 when "this_year"
                   Time.zone.now.beginning_of_year..Time.zone.now.end_of_year
                 end

    base_query = select("products.*, SUM(order_items.quantity)
                          AS total_quantity")
                 .joins(:order_items)
                 .joins("JOIN orders ON orders.id = order_items.order_id")
                 .group("products.id")
                 .where.not(orders: {status: 4})
                 .order("total_quantity DESC")
                 .limit(Settings.top_sell.limit)
    if time_range
      base_query.where("orders.created_at BETWEEN ? AND ?", time_range.first,
                       time_range.last)
    else
      base_query
    end
  end)

  def self.ransackable_attributes _auth_object = nil
    %w(
      category_id
      created_at
      description
      id
      price
      product_name
      rating
      sold
      stock
      updated_at
    )
  end

  def self.ransackable_associations _auth_object = nil
    %w(carts category feedbacks image_attachment image_blob order_items)
  end

  def update_rating
    if feedbacks.any?
      average_rating = feedbacks.average(:rating).to_f
      rounded_rating = average_rating.round(1)
      update(rating: rounded_rating)
    else
      update(rating: 0)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :find_product, only: %i(edit update destroy)
  before_action :default_categories, only: %i(new create edit update index)
  def index
    @q = Product.ransack(params[:q] || {})
    @query = params.dig(:q, :product_name_cont) || nil
    session[:search_query] = @query
    @pagy, @products_search = pagy(
      @q.result,
      limit: Settings.page_10
    )
    render :index
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    @product.rating = 0
    if @product.save
      flash[:success] = t "admin.products.create.messages.success"
      redirect_to admin_products_path q: {product_name_cont:
                                          @product.product_name}
    else
      flash[:error] = t "admin.products.create.messages.error"
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = t "admin.products.update.messages.success"
      redirect_to admin_products_path q: {product_name_cont:
                                          session[:search_query]}
      session.delete(:search_query)
    else
      flash[:error] = t "admin.products.update.messages.error"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t "admin.products.destroy.messages.success"
      redirect_to admin_products_path q: {product_name_cont:
                                          session[:search_query]}
    else
      flash[:error] = t "admin.products.destroy.messages.error"
    end
    session.delete(:search_query)
  end

  private

  def product_params
    params.require(:product).permit Product::PRODUCT_PARAMS
  end

  def find_product
    @product = Product.find_by id: params[:id]

    return if @product

    flash[:warning] = t "flash.not_found_product"
    redirect_to admin_products_path q: {product_name_cont:
                                        session[:search_query]}
  end

  def default_categories
    @categories = Category.all
  end
end

app/controllers/api/v1/admin/products_controller.rb
class Api::V1::Admin::ProductsController < AdminController
  skip_before_action :verify_authenticity_token
  before_action :find_product, only: %i(edit update destroy)
  before_action :default_categories, only: %i(new create edit update index)

  def index
    @q = Product.ransack(params[:q] || {})
    @query = params.dig(:q, :product_name_cont) || nil
    @products_search = @q.result
    render json: @products_search, each_serializer: ProductSerializer
  end

  def new
    @product = Product.new
    render json: @product
  end

  def create
    @product = Product.new product_params
    @product.rating = 0
    if @product.save
      render json: {
        message: t("admin.products.create.messages.success"),
        product: ProductSerializer.new(@product)
      }, status: :created
    else
      render json: {errors: t("admin.products.create.messages.error")},
             status: :unprocessable_entity
    end
  end

  def edit
    render json: @product, serializer: ProductSerializer
  end

  def update
    if @product.update product_params
      render json: {
        message: t("admin.products.update.messages.success"),
        product: ProductSerializer.new(@product)
      }, status: :ok
    else
      render json: {errors: t("admin.products.update.messages.error")},
             status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      render json: {message: t("admin.products.destroy.messages.success")},
             status: :ok
    else
      render json: {errors: t("admin.products.destroy.messages.error")},
             status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit Product::PRODUCT_PARAMS
  end

  def find_product
    @product = Product.find_by id: params[:id]
    return if @product

    render json: {errors: t("flash.not_found_product")}, status: :not_found
  end

  def default_categories
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource only: :show
  def search
    @categories = Category.all
    @query = params[:q][:product_name_cont]
    session[:search_query] = @query
    @products_search = if @query.blank?
                         Product.all
                       else
                         fetch_search_results(@query)
                       end
    if @products_search.present?
      @pagy, @products_search = pagy_results(@products_search)
    else
      @products_search = Product.none
    end

    @total_results = @products_search.size
    render :search
  end

  def filter_by_category
    @categories = Category.all
    @query = session[:search_query]

    if @query.present?
      @products_filtered = fetch_filtered_results(@query, params[:q])
      @pagy, @products_filtered = pagy_results(@products_filtered)
    else
      @products_filtered = Product.none
    end

    @total_results = @products_filtered.size
    render :search
  end

  def show
    update_product_rating
    load_feedbacks
    load_cart_for_current_user
  end

  private

  def update_product_rating
    @product.update_rating
  end

  def load_feedbacks
    @feedbacks = @product.feedbacks
                         .includes(:user)
                         .sort_by_field(params[:sort_by], params[:direction])
  end

  def load_cart_for_current_user
    return unless current_user

    @cart = current_user.carts.find_by(product_id: @product.id)
  end

  def fetch_search_results query
    search_results = Product.search(query).results
    product_ids = search_results.map(&:_id)
    Product.where(id: product_ids)
  end

  def fetch_filtered_results query, filters
    filtered_results = Product.search(
      query,
      category_id: filters[:category_id_eq],
      price_gteq: filters[:price_gteq],
      price_lteq: filters[:price_lteq],
      rating_gteq: filters[:rating_gteq]
    ).results
    product_ids = filtered_results.map(&:_id)
    Product.where(id: product_ids)
  end

  def pagy_results products
    pagy(products, items: Settings.page_10)
  end
end

app/views/admin/products/_admin_product_list.html.erb
<div class="product-list">
  <div class="product-item">
    <div class="product-info">
      <p class="product-id"><%= product.id %></p>
      <%= image_tag(resized_image(product), alt: product.product_name, class: "product-image") %>
      <div class="product-details">
        <h2 class="product-name"><%= product.product_name %></h2>
        <p class="product-description"><%= product.description %></p>
        <div class="product-rating">
            <span class="star-icon">★</span><%= product.rating %>
        </div>
      </div>
    </div>
    <p class="product-category"><%= product.category.category_name %></p>
    <p class="product-price"><%= format_currency product.price %></p>
    <p class="product-stock"><%= product.stock %></p>
    <p class="product-sold"><%= product.sold %></p>
    <div class="product-actions">
      <%= link_to edit_admin_product_path(product), class: "edit-button" do %>
        <%= image_tag "edit_icon.png", alt: "Edit", class: "icon" %>
      <% end %>
      <%= button_to admin_product_path(product), method: :delete, data: { controller: "confirm", action: "turbo:submit-start->confirm#submitWithConfirmation", turbo_confirm: t("admin.products.destroy.messages.confirm_delete") }, class: "delete-button" do %>
        <%= image_tag "delete_icon.webp", alt: "Delete", class: "icon" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= render "shared/error_messages", object: @product %>

<%= form_with model: [:admin, @product], local: true do |f| %>
  <div class="product_info">
    <div class="form-group">
      <%= f.label :category_id do %>
        <%= t("admin.products.form.category") %> <span class="required">*</span>
      <% end %>
      <div class="select-wrapper">
        <%= f.collection_select :category_id, @categories, :id, :category_name, {prompt: t("admin.products.form.select_category")}, {class: "form-control custom-select", required: true} %>
        <img src="/assets/arrow_down.png" alt="Dropdown Arrow" class="select-arrow">
      </div>
    </div>

    <div class="image-name">
      <div class="form-group">
        <%= f.label :image do %>
          <%= t("admin.products.form.image") %> <span class="required">*</span>
        <% end %>
        <%= f.file_field :image, class: "form-control-file", id: "image_input", required: action_name == "new" %>
        <% if @product.image.attached? %>
          <img id="preview_image" src="<%= url_for(@product.image) %>" alt="Current Image" style="max-width: 200px; margin-top: 10px;" />
        <% else %>
          <img id="preview_image" src="#" alt="Image Preview" style="display: none; max-width: 200px; margin-top: 10px;" />
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :product_name do %>
          <%= t("admin.products.form.product_name") %> <span class="required">*</span>
        <% end %>
        <%= f.text_field :product_name, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, t("admin.products.form.description") %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="price-stock">
      <div class="form-group">
        <%= f.label :price do %>
          <%= t("admin.products.form.price") %> <span class="required">*</span>
        <% end %>
        <%= f.number_field :price, class: "form-control", placeholder:  "#{Settings.suggest_price}",required: true %>
      </div>
      <div class="form-group">
        <%= f.label :stock, t("admin.products.form.stock") %>
        <%= f.number_field :stock, class: "form-control" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit t("admin.products.form.submit"), class: "btn btn-primary" %>
      <%= link_to t("admin.products.form.cancel"), admin_products_path(q: {product_name_cont: session[:search_query]}), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<% provide :title, t("admin.products.edit.title") %>
<div class="crud_product">
  <p class="crud-title"><%= t "admin.products.edit.title" %></p>
  <%= render partial: "form", product: @product %>
</div>

app/views/admin/products/index.html.erb
<div class="admin-product-show">
  <%= search_form_for @q, url: admin_products_path, method: :get, local: true, class: "d-flex mx-3 flex-grow-1 justify-content-center" do |f| %>
    <%= f.text_field :product_name_cont,value: @query, class: "form-control me-2 custom-search", placeholder: t("layouts.header.search.placeholder"), aria: { label: t("layouts.header.search.placeholder") } %>
    <%= f.submit t("layouts.header.search.search_button"), class: "btn btn-outline-success" do %>
      <i class="bi bi-search"></i>
    <% end %>
  <% end %>

  <div class="filter_show">
    <div class="col-md-3 filter-frame">
      <%= search_form_for @q, url: admin_products_path, method: :get do |f| %>
        <div class="form-group">
          <%= f.label :category_id_eq, t("products.search.category") %>
          <%= f.collection_select :category_id_eq, @categories, :id, :category_name, {include_blank: true}, {class: "form-control"} %>
        </div>
        <%= f.hidden_field :product_name_cont, value: @query %>

        <div class="form-group">
          <%= f.label :price_range, t("products.search.price_range") %>
          <div class="price-range-filter__inputs d-flex align-items-center">
            <%= f.number_field :price_gteq, class: "form-control me-2", min: 0 %>
            <span class="me-2">-</span>
            <%= f.number_field :price_lteq, class: "form-control ms-2", min: 0 %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :rating_gteq, t("products.search.rating_min") %>
          <%= f.number_field :rating_gteq, class: "form-control", step: 0.1, min: 0 %>
        </div>

        <%= f.submit t("products.search.filter"), class: "btn btn-primary" %>
      <% end %>
    </div>

    <div>
      <div class="sort-product">
        <div class="sort-by">
            <%= sort_link @q, :rating, t("products.search.rating") %>
          </div>
          <div class="sort-by">
            <%= sort_link @q, :price, t("products.search.price") %>
          </div>
          <div class="sort-by">
            <%= sort_link @q, :sold, t("products.search.sold") %>
          </div>
          <%= link_to t("admin.products.add_product.add_button"), new_admin_product_path, class: "add-button" %>
      </div>
      <div>
        <div class="title-line">
          <p><%= t "admin.products.show_title.product" %></p>
          <p><%= t "admin.products.show_title.category" %></p>
          <p><%= t "admin.products.show_title.price" %></p>
          <p><%= t "admin.products.show_title.stock" %></p>
          <p><%= t "admin.products.show_title.sold" %></p>
          <p><%= t "admin.products.show_title.edit" %></p>
          <p><%= t "admin.products.show_title.delete" %></p>
        </div>
        <% if @products_search.present? %>
          <%= render partial: "admin/products/admin_product_list", collection: @products_search, as: :product %>
        <% elsif @products_filtered.present? %>
          <%= render partial: "admin/products/admin_product_list", collection: @products_filtered, as: :product %>
        <% end %>
        <%== pagy_bootstrap_nav @pagy %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, t("admin.products.new.title") %>
<div class="crud_product">
  <p class="crud-title"><%= t "admin.products.new.title" %></p>
  <%= render partial: "form", product: @product %>
</div>